# Generated by Django 3.0.2 on 2020-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=None)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discripsion', models.TextField(max_length=500)),
            ],
        ),
    ]
