# Generated by Django 3.0.3 on 2020-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='restaurants/images/')),
                ('sub_text', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('discripsion', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=500)),
                ('offer', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('activate', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
